# Numpy arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3], [4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,11,2) # Аналог range в классическом python

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3) # Create an array of 0

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0, 5, 10) # Разделение вектора на равные отрезки

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)

array([0.37724668, 0.73859491, 0.62813195, 0.02750169, 0.08826377])

In [20]:
np.random.rand(5,5)

array([[0.27904657, 0.73313941, 0.51092873, 0.95370897, 0.80385368],
       [0.54734416, 0.33975457, 0.62445783, 0.50752173, 0.32902921],
       [0.39799767, 0.1322669 , 0.63044328, 0.5623284 , 0.97298089],
       [0.56141899, 0.79212773, 0.27822013, 0.76912157, 0.41819671],
       [0.41240823, 0.16832813, 0.64424461, 0.60666426, 0.1412721 ]])

In [22]:
np.random.randn(4,4) # Random по нормальному распределению

array([[-0.29011743, -0.24743499, -0.69334902,  1.42753418],
       [ 0.38631702,  0.05786803,  1.78420212, -0.57445357],
       [-0.46679543,  0.14042261, -0.50870813, -0.47639032],
       [-0.66427668, -0.87736889, -0.12423246, -1.11635872]])

In [23]:
np.random.randint(1, 100) # Random integer number (from minimum to maximum)

68

In [24]:
arr = np.arange(25)

In [25]:
ranarr = np.random.randint(0, 50, 10)

In [33]:
arr = arr.reshape(5,5) # Преобразовать массив в другую форму

In [27]:
ranarr.max()
ranarr.min()

9

In [29]:
ranarr.argmax() # Index of maximal value
ranarr.argmin() # Index of minimum value

4

In [34]:
arr.shape # Shape of array

(5, 5)

In [35]:
arr.dtype # Type of elements in array

dtype('int32')

In [36]:
from numpy.random import randint

In [38]:
randint(2,10)

5

# Indexing and selection

In [39]:
import numpy as np

In [41]:
arr = np.arange(0, 11)

In [42]:
arr[8]

8

In [43]:
arr[1:5]

array([1, 2, 3, 4])

In [44]:
arr[0:5] = 100

In [45]:
slice_of_arr = arr[0:6]

In [46]:
slice_of_arr [:] = 99

In [47]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [48]:
arr_copy = arr.copy() # Копирование массива, без влияния на него при внесении изменений

In [50]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [51]:
arr_2d[1,1] # Обращение к элементу многомерного массива

25

In [52]:
arr_2d[:2, 1:] # Обращение к набору элементов многомерного массива

array([[10, 15],
       [25, 30]])

In [53]:
arr = np.arange(1,11)

In [55]:
bool_arr = arr > 5 # Select elements from array (elements type in boolean)

In [57]:
arr[bool_arr] # Save elements to array (elements type as like as in original array)

array([ 6,  7,  8,  9, 10])

In [58]:
arr[arr > 5] # Same as previos rows of code

array([ 6,  7,  8,  9, 10])

In [59]:
arr_2d = np.arange(50).reshape(5,10)

In [60]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

# Numpy operations
Array with Array
<br>Array with Scolars
<br>Universal array functions

In [61]:
import numpy as np

In [62]:
arr = np.arange(0,11)

In [63]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# Homework

In [65]:
import numpy as np

In [66]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [69]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [73]:
np.arange(5,5,10)

array([], dtype=int32)

In [76]:
arr2 = np.arange(0,10)
arr2[:11] = 5

In [77]:
arr2

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [82]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [84]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [88]:
np.random.rand(1)

array([0.91610209])

In [89]:
np.random.randn(25)

array([-1.1355368 , -0.73819752, -0.37044861, -0.82052356,  0.02261705,
        1.25444443, -0.4433395 ,  1.52692112,  1.63985512, -0.10336263,
       -0.62227676, -0.48430259,  0.90557772, -0.7640306 ,  0.63276002,
       -0.00882214,  0.3341932 ,  0.49845748, -0.51366229,  0.18886604,
       -1.18785043, -0.28209986, -1.31770017, -0.07501668,  0.5729595 ])

In [91]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])